[build]
  base = "frontend"
  command = "npm run build"
  # Let the Next.js plugin handle the publish dir, don’t force it
  publish = "frontend/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
